#!/usr/bin/env python
"""Prompt-expansion diagnostic (appendix): expanded vs original prompts.

Five benchmark cases were regenerated by Cosmos-3 and Wan-2.7 with three
expanded prompts each (data/ego2act/<case>_expanded<N>/prompt.txt: the original goal
followed by a detailed shot-level scene description), three seeds per prompt,
and scored by Ego2ActJudge against the original goal
(analysis/csv/prompt_expansion_scores.jsonl). Original-prompt scores are the benchmark
judge scores of the same case, generator and seeds (analysis/csv/scores_ego2act.csv).
Final uses scoring.final_score, so unattempted videos count as 0.

Outputs analysis/results/prompt_expansion.json.
"""
from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path
from statistics import mean

from scoring import final_score

HERE = Path(__file__).resolve().parent
DATA = HERE.parent / "analysis" / "csv"
MODELS = ["cosmos_3", "wan_2_7"]


def number(v):
    return None if v in ("", None) else float(v)


def main():
    expanded = defaultdict(list)  # (case, model, variant) -> finals
    for line in (DATA / "prompt_expansion_scores.jsonl").read_text().splitlines():
        r = json.loads(line)
        case, variant = r["case_id"].rsplit("_expanded", 1)
        model = r["video_id"].split("/")[2]
        s = final_score(r.get("ovr_task"), r.get("ovr_phy"), r.get("final"))
        if s is not None:
            expanded[case, model, variant].append(s)
    cases = sorted({c for c, _, _ in expanded})
    original = defaultdict(list)
    with (DATA / "scores_ego2act.csv").open(newline="") as stream:
        for r in csv.DictReader(stream):
            if r["case_id"] in cases and r["model"] in MODELS:
                s = final_score(number(r["ego2act_task"]), number(r["ego2act_physics"]), number(r["ego2act_score"]))
                if s is not None:
                    original[r["case_id"], r["model"]].append(s)
    rows, summary = [], {}
    for model in MODELS:
        deltas, orig_means, exp_means = [], [], []
        for case in cases:
            o = mean(original[case, model])
            orig_means.append(o)
            for variant in ("1", "2", "3"):
                e = mean(expanded[case, model, variant])
                exp_means.append(e)
                deltas.append(e - o)
                rows.append({"case": case, "model": model, "variant": variant, "original": o, "expanded": e,
                             "delta": e - o, "videos": len(expanded[case, model, variant])})
        summary[model] = {"original_mean": mean(orig_means), "expanded_mean": mean(exp_means),
                          "mean_delta": mean(deltas), "positive": sum(d > 0 for d in deltas), "prompts": len(deltas),
                          "min_delta": min(deltas), "max_delta": max(deltas)}
    (HERE / "results/prompt_expansion.json").write_text(json.dumps({"cases": cases, "summary": summary, "rows": rows}, indent=2) + "\n")
    print(cases)
    for m, s in summary.items():
        print(m, {k: round(v, 1) if isinstance(v, float) else v for k, v in s.items()})
    for case in cases:
        print(case, {m: (round(mean(original[case, m]), 1), [round(mean(expanded[case, m, v]), 1) for v in "123"]) for m in MODELS})


if __name__ == "__main__":
    main()
